Fix/pricing gradients and rotations
lucidlynxproject/web pull request #4
Opened 2022-08-18 11:53 UTC by JavWe

Arreglado tamaño y separación navbar, y ocultar login, cambio seccion de pricin por dos tarjetas, gratis y business, añadido gradiente al componente rectángulo y ajuste de paleta de colores en las variables.

2022-08-18 17:04 UTC, adabaed requested changes
@JavWe @HeyMita está todo genial, quizás deberíamos quitar el "Every plan includes 30 day free trial" ya que con los cambios que hemos hablado esto está fuera de lugar.

2022-08-18 18:46 UTC, HeyMita commented
@adabaed Perfecto se lo comento a @JavWe y nos ponemos a ello, miraré el trello para ajustar la tarea y solucionarlo lo antes posible.🐱‍🏍

2022-08-19 10:30 UTC, JavWe commented
> @JavWe @HeyMita está todo genial, quizás deberíamos quitar el "Every plan includes 30 day free trial" ya que con los cambios que hemos hablado esto está fuera de lugar.

Eliminado el subtitulo "Every plan includes 30 day free trial" y ajustado el margen entre secciones que se quedaba raro al eliminar eso.

2022-08-19 10:59 UTC, lucidlynxproject commented
Perfecto!!!! 🚀🍆

2022-08-19 10:59 UTC, merged